### ISSUE TITLE
Error: Failed to load plugin meteor: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by lnmunhoz** [dferber90/eslint-plugin-meteor#364]
I followed the code-style guide on [https://guide.meteor.com/code-style.html](https://guide.meteor.com/code-style.html) but I am getting the following error on linting (using atom).

```
Error: Failed to load plugin meteor: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/Users/lnmunhoz/workspaces/project/x/node_modules/babel-polyfill/lib/index.js:12:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/lnmunhoz/workspaces/project/x/node_modules/eslint-plugin-meteor/dist/index.js:8:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

This is my .eslintrc
```json
{
  "plugins": [
    "meteor"
  ],
  "extends": [
    "airbnb",
    "plugin:meteor/recommended"
  ],
  "rules": {
    "no-underscore-dangle": ["error", { "allow": ["_id", "_d"] }]
  },
  "settings": {
    "import/resolver": "meteor"
  },
  "globals": {
    "Package": true
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "experimentalObjectRestSpread": true,
      "jsx": true
    },
    "syntax_map": {
      "JavaScript (Babel)": "javascript",
    }
  }
}
```

Any thoughts why this is happening?

**Comment by dferber90** [comment]
Can you try `npm install --save-dev eslint-plugin-meteor@4.0.1` and see whether that fixes your problem?

**Comment by dferber90** [comment]
Feel free to reopen the issue in case that didn't solve it.
